Requirement already satisfied: heroku in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (0.1.4)
Requirement already satisfied: requests>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from heroku) (2.28.1)
Collecting python-dateutil==1.5
  Using cached python-dateutil-1.5.tar.gz (233 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=1.0.0->heroku) (2022.6.15)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=1.0.0->heroku) (1.26.10)
Requirement already satisfied: charset-normalizer<3,>=2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=1.0.0->heroku) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=1.0.0->heroku) (3.3)
Using legacy 'setup.py install' for python-dateutil, since package 'wheel' is not installed.
Installing collected packages: python-dateutil
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.2
    Uninstalling python-dateutil-2.8.2:
